on: 
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  package:
    permissions:
      packages: write
    runs-on: alpine-lxc
    steps:
      - name: login
        uses: docker/login-action@v1
        with:
          registry: git.gay
          username: finite-actions-bot
          password: ${{secrets.ACCONT_TOKEN}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        working-directory: KodeRunner-Docker-Alpine/ 
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: "KodeRunner-Docker-Alpine/Dockerfile"
          context: "{{defaultContext}}"
          push: true
          tags: git.gay/finite/koderunner:test
      - name: Cleanup
        run: |
          docker logout
    


          