on: workflow_dispatch
jobs:
  build:
    runs-on: docker
    steps:
      - run: apt-get update
      - name: get system deps
        run: apt-get install -y libicu-dev
      - uses: actions/checkout@v3
      - uses: https://github.com/actions/setup-dotnet@v4
        with:
          global-json-file: runner/globals.json
          working-directory: runner/
      - name: build KodeRunner
        run: dotnet publish .
        working-directory: runner/
      - 
        name: archive artifact
        run: tar czvf ../../../../../upload.tar.gz .
        working-directory: runner/bin/Release/net8.0/publish/
      - uses: actions/upload-artifact@v3
        with:
          name: ci-cached-runner
          path: upload.tar.gz
      - 
        name: build runners
        working-directory: KodeRunnerLibs/
        run: dotnet publish .


          