on: workflow_dispatch
jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v3
      - uses: https://github.com/actions/setup-dotnet@v4
        with:
          global-json-file: runner/globals.json
          working-directory: runner/
      - run: dotnet publish .
        working-directory: runner/