import java.util.HashMap;
import java.util.Map;

public class LanguageConfig {
    private static final Map<String, LanguageInfo> languages = new HashMap<>();
    
    static {
        // Initialize language configurations
        languages.put("python", new LanguageInfo(
            "python", ".py", "#", "# ", 
            "print(\"Hello from KodeRunner!\")\nprint(\"Python project ready!\")"
        ));
        
        languages.put("csharp", new LanguageInfo(
            "csharp", ".cs", "//", "// ",
            "using System;\n\nclass Program\n{\n    static void Main()\n    {\n        Console.WriteLine(\"Hello from KodeRunner!\");\n        Console.WriteLine(\"C# project ready!\");\n    }\n}"
        ));
        
        languages.put("nodejs", new LanguageInfo(
            "nodejs", ".js", "//", "// ",
            "console.log(\"Hello from KodeRunner!\");\nconsole.log(\"Node.js project ready!\");"
        ));
        
        languages.put("c", new LanguageInfo(
            "c", ".c", "//", "// ",
            "#include <stdio.h>\n\nint main()\n{\n    printf(\"Hello from KodeRunner!\\n\");\n    printf(\"C project ready!\\n\");\n    return 0;\n}"
        ));
        
        languages.put("j-masm", new LanguageInfo(
            "j-masm", ".masm", ";", "; ",
            "lbl main\nmov RAX 1\nmov RBX 2\nadd RAX RBX\nout 1 RAX\nhlt"
        ));
        
        languages.put("java", new LanguageInfo(
            "java", ".java", "//", "// ",
            "public class Main {\n    public static void main(String[] args) {\n        System.out.println(\"Hello from KodeRunner!\");\n        System.out.println(\"Java project ready!\");\n    }\n}"
        ));
        
        languages.put("go", new LanguageInfo(
            "go", ".go", "//", "// ",
            "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello from KodeRunner!\")\n    fmt.Println(\"Go project ready!\")\n}"
        ));
        
        languages.put("rust", new LanguageInfo(
            "rust", ".rs", "//", "// ",
            "fn main() {\n    println!(\"Hello from KodeRunner!\");\n    println!(\"Rust project ready!\");\n}"
        ));
    }
    
    public static LanguageInfo getLanguageInfo(String language) {
        return languages.getOrDefault(language.toLowerCase(), 
            new LanguageInfo(language, ".txt", "#", "# ", "// Default template"));
    }
    
    public static String[] getSupportedLanguages() {
        return languages.keySet().toArray(new String[0]);
    }
    
    public static String generateHeader(String language, String projectName, String fileName) {
        LanguageInfo info = getLanguageInfo(language);
        StringBuilder header = new StringBuilder();
        
        header.append(info.commentPrefix).append("Project: ").append(projectName).append("\n");
        header.append(info.commentPrefix).append("File_name: ").append(fileName).append("\n");
        header.append(info.commentPrefix).append("Language: ").append(language).append("\n");
        header.append(info.commentPrefix).append("Generated by KodeRunner Desktop Tester").append("\n");
        header.append(info.commentPrefix).append("").append("\n");
        
        return header.toString();
    }
    
    public static class LanguageInfo {
        public final String name;
        public final String extension;
        public final String commentStyle;
        public final String commentPrefix;
        public final String template;
        
        public LanguageInfo(String name, String extension, String commentStyle, 
                          String commentPrefix, String template) {
            this.name = name;
            this.extension = extension;
            this.commentStyle = commentStyle;
            this.commentPrefix = commentPrefix;
            this.template = template;
        }
    }
}
