<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
<!-- <Reference Include="SharpMASM">
  <HintPath>../../SharpMASM/bin/Debug/net8.0/SharpMASM.dll</HintPath>
  <HintPath>../../SharpMASM/bin/Release/net8.0/SharpMASM.dll</HintPath>
</ItemGroup> -->
<ItemGroup>
  <PackageReference Include="PythonNET" Version="3.0.4" />
</ItemGroup>
<ItemGroup>
  <ProjectReference Include="..\..\runner\KodeRunner.csproj" />
</ItemGroup>
	<Target Name="AfterBuild">
		<Message Text="Copying $(TargetPath) to ..\..\runner\koderunner\Runnables" Importance="high" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="..\..\runner\koderunner\Runnables" />
		
	</Target>
</Project>
